# Generated by Django 5.1.4 on 2025-01-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='taskTitle',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='taskdesc',
        ),
    ]
