# Generated by Django 5.1.4 on 2025-01-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_task_taskdesc_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
